# Generated by Django 4.2.2 on 2023-06-29 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Committee",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(blank=True, max_length=50, null=True)),
                ("description", django_quill.fields.QuillField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(blank=True, max_length=50, null=True)),
                ("description", django_quill.fields.QuillField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("first_name", models.CharField(blank=True, max_length=50, null=True)),
                ("last_name", models.CharField(blank=True, max_length=50, null=True)),
                ("primary_phone", models.CharField(blank=True, max_length=15, null=True)),
                ("secondary_phone", models.CharField(blank=True, max_length=15, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                ("designation", models.CharField(blank=True, max_length=50, null=True)),
                ("join_date", models.DateField(blank=True, null=True)),
                ("is_available", models.BooleanField(default=True)),
                ("on_leave", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="meetings.department"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MeetingType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(blank=True, max_length=50, null=True)),
                ("meeting_type_description", django_quill.fields.QuillField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="meetings.department"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Meeting",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(blank=True, max_length=50, null=True)),
                ("description", django_quill.fields.QuillField(blank=True, null=True)),
                ("content", django_quill.fields.QuillField(blank=True, null=True)),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pending", "Pending"),
                            ("ongoing", "Ongoing"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("content_document", models.FileField(blank=True, null=True, upload_to="documents/")),
                (
                    "acknowledged_member",
                    models.ManyToManyField(blank=True, related_name="acknowledged_member", to="meetings.member"),
                ),
                (
                    "attended_member",
                    models.ManyToManyField(blank=True, related_name="attended_member", to="meetings.member"),
                ),
                (
                    "committee",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="meetings.committee"
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="meetings.department"
                    ),
                ),
                (
                    "invited_member",
                    models.ManyToManyField(blank=True, related_name="invited_member", to="meetings.member"),
                ),
                (
                    "meeting_type",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="meetings.meetingtype"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="committee",
            name="department",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="meetings.department"
            ),
        ),
        migrations.AddField(
            model_name="committee",
            name="member",
            field=models.ManyToManyField(blank=True, to="meetings.member"),
        ),
    ]
