# Generated by Django 4.2.2 on 2023-06-30 17:26

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):
    dependencies = [
        ("meetings", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="meeting",
            old_name="end_time",
            new_name="meeting_time",
        ),
        migrations.RemoveField(
            model_name="meeting",
            name="content_document",
        ),
        migrations.RemoveField(
            model_name="meeting",
            name="meeting_type",
        ),
        migrations.RemoveField(
            model_name="meeting",
            name="start_time",
        ),
        migrations.RemoveField(
            model_name="meeting",
            name="status",
        ),
        migrations.RemoveField(
            model_name="member",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="member",
            name="is_available",
        ),
        migrations.RemoveField(
            model_name="member",
            name="join_date",
        ),
        migrations.RemoveField(
            model_name="member",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="member",
            name="on_leave",
        ),
        migrations.AddField(
            model_name="member",
            name="full_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="committee",
            name="description",
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="committee",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="department",
            name="description",
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="department",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="content",
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="description",
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="member",
            name="designation",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="member",
            name="primary_phone",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="member",
            name="secondary_phone",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name="MeetingType",
        ),
    ]
