# Generated by Django 4.2.2 on 2024-01-11 21:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("meetings", "0002_rename_end_time_meeting_meeting_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="committee",
            name="description",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="department",
            name="description",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="content",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="description",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
