# Generated by Django 4.2.2 on 2024-01-11 21:37

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meetings", "0003_alter_committee_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Content",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("content", ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="meeting",
            name="content",
        ),
        migrations.AddField(
            model_name="meeting",
            name="content",
            field=models.ManyToManyField(blank=True, to="meetings.content"),
        ),
    ]
