# Generated by Django 4.2.2 on 2024-01-12 10:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("meetings", "0005_rename_content_meeting_agenda"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="meeting",
            name="agenda",
        ),
        migrations.AddField(
            model_name="meeting",
            name="agenda",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
